server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
	datasource:
		url: jdbc:postgresql://ec2-54-235-86-226.compute-1.amazonaws.com:5432/d6k3mh7iegl2mj?useSSL=true&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
		username: tieyiexrpkzxop
		password: db828c317d53f062b56aecf8af7230898083a7cbd96f5e3e069beb24052837c7
		driver-class-name: org.postgresql.Driver

	jpa:
		hibernate:
			ddl-auto: update
		show-sql: true		

security:
	oauth2:
		resource:
			filter-order: 3

