
server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        data: classpath:/sql/data.sql
        schema: classpath:/sql/schema.sql
        driver-class-name: org.postgresql.Driver
        username: tieyiexrpkzxop
        password: 'db828c317d53f062b56aecf8af7230898083a7cbd96f5e3e069beb24052837c7'
        platform: org.hibernate.dialect.PostgreSQLDialect
        url: jdbc:postgres://ec2-54-235-86-226.compute-1.amazonaws.com:5432/d6k3mh7iegl2mj&useSSL=true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
